platform :ios, '7.0'
#pod 'Reachability', '~> 3.1.1'
pod 'AFNetworking', '~> 1.3.1'
#pod 'AFNetworking', '~> 2.3'
pod 'hpple', '~> 0.2.0'
#pod 'IGHTMLQuery'
pod 'FlatUIKit', '~> 1.4'
pod 'UITableView-NXEmptyView'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.9'